version: '3'
services:
  drawio:
    container_name: drawio_sub
    image: jgraph/drawio
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    ports:
      - 8086:8080
    labels:
      - com.centurylinklabs.watchtower.enable=1

  collabora:
    image: collabora/code
    container_name: collabora_sub
    restart: unless-stopped
    environment:
      - username=admin
      - password=test123
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    ports:
      - 9980:9980
    labels:
      - com.centurylinklabs.watchtower.enable=1

  libreoffice:
    image: lscr.io/linuxserver/libreoffice
    container_name: libreoffice_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /home/docker/docker_shared/libreoffice:/config
    ports:
      - 3000:3000
    labels:
      - com.centurylinklabs.watchtower.enable=1
