version: '3'

services:

  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /mnt/vmdata/vsCode:/config
    ports:
      - 8443:8443
    labels:
      - com.centurylinklabs.watchtower.enable=1
      
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower_sub
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - WATCHTOWER_POLL_INTERVAL=43200     # Poll interval in seconds
      - WATCHTOWER_INCLUDE_STOPPED=1       # Include stopped containers
      - WATCHTOWER_REVIVE_STOPPED=0        # Restart stopped containers
      - WATCHTOWER_CLEANUP=1               # Delete unused image
      - WATCHTOWER_LABEL_ENABLE=1          # Only update containers that have a 'com.centurylinklabs.watchtower.enable' label set to true.
      - WATCHTOWER_MONITOR_ONLY=0          # monitor-only can be specified on a per-container basis with the 'com.centurylinklabs.watchtower.monitor-only' label set.
      - WATCHTOWER_LIFECYCLE_HOOKS=0       # Enable pre/post-update scripts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.centurylinklabs.watchtower.enable=1
    
  dozzle:
    container_name: dozzle_sub
    image: amir20/dozzle:latest
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    labels:
      - com.centurylinklabs.watchtower.enable=1
      
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /home/docker/config/heimdall:/config
    ports:
      - 8000:80
      - 8441:443
    labels:
      - com.centurylinklabs.watchtower.enable=1
  
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /home/docker/config/syncthing:/config
      - /mnt/vmdata:/vmdata
      - /mnt/sda:/sda
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    labels:
      - com.centurylinklabs.watchtower.enable=1
      
  duplicati:
    image: duplicati/duplicati
    container_name: duplicati_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
#      - CLI_ARGS= #optional
    volumes:
      - /home/docker/config/duplicati:/config
      - /home/docker/duplicati:/data
      - /mnt/sda/duplicati_backup:/backups
      - /home/docker:/source
    ports:
      - 8200:8200
    labels:
      - com.centurylinklabs.watchtower.enable=1
