version: '3'

services:

  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /mnt/vmdata/vsCode:/config
    ports:
      - 8443:8443

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower_sub
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 3 * * *" --cleanup --remove-volumes
    
  dozzle:
    container_name: dozzle_sub
    image: amir20/dozzle:latest
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /home/docker/config/heimdall:/config
    ports:
      - 8000:80
      - 8441:443

  duplicati:
    image: duplicati/duplicati
    container_name: duplicati_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
#      - CLI_ARGS= #optional
    volumes:
      - /home/docker/config/duplicati:/config
      - /home/docker/duplicati:/data
      - /mnt/sda/duplicati_backup:/backups
      - /home/docker:/source
    ports:
      - 8200:8200
