version: "3"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/mods:code-server-python3
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /mnt/ctdata/docker_shared/code-server:/config
    ports:
      - 8443:8443
    labels:
      - com.centurylinklabs.watchtower.enable=1
