version: '3'

services:

  Aria2-Pro:
    container_name: aria2-pro_sub
    image: p3terx/aria2-pro
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - UMASK_SET=022
      - RPC_SECRET=P3TERX
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=true
      - UPDATE_TRACKERS=true
      - TZ=America/New_York
    volumes:
      - /home/docker/config/aria2:/config
      - /mnt/dataCT/aria2:/downloads
    network_mode: bridge
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m

# AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang_sub
    image: p3terx/ariang
    restart: unless-stopped
    command: --port 6880 --ipv6
    network_mode: bridge
    ports:
      - 6880:6880
    logging:
      driver: json-file
      options:
        max-size: 1m

#   baidupcs:
#     image: auska/docker-baidupcs
#     container_name: baidupcs_sub
#     restart: unless-stopped
#     environment:
#       - PGID=1001
#       - PUID=113
#       - TZ=America/New_York
#     ports:
# #      - "9999:999"
#       - "1999:1999"
#     volumes:
#       - /mnt/dataCT/baidu:/mnt

  portainer:
     image: portainer/portainer-ce
     container_name: portainer_sub
     restart: unless-stopped
     ports:
       - "9000:9000"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /home/docker/portainer_data:/data
     environment:
       - TZ=America/New_York

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - WEBUI_PORT=6881
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - /home/docker/config/qbittorrent:/config     
      - /mnt/dataCT/qbittorrent:/downloads
    ports:
      - "6882:6882"
      - "6882:6882/udp"
      - "6881:6881" 

  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /mnt/dataCT/vsCode:/config
    ports:
      - 8443:8443

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /home/docker/config/jellyfin:/config
      - /mnt/dataCT/cache/jellyfin:/cache
      - /mnt/dataCT/aria2/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional

  ouroboros:
    image: pyouroboros/ouroboros
    container_name: ouroboros_sub
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/New_York
      - LOG_LEVEL=info
      - INTERVAL=36000
      - SELF_UPDATE=true
      - CLEANUP=true
#      - NOTIFIERS="mailtos://mydomain.com:587?user=notify@mydomain.com&pass=mypassword&smtp=192.168.6.98&to=user@mydomain.com"
#      - IGNORE="clash_sub mail_sub mariadb_sub phpmyadmin_sub qbittorrent_sub"

  dozzle:
    container_name: dozzle_sub
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /home/docker/config/heimdall:/config
    ports:
      - 8000:80
      - 8441:443
