version: '3'

services:

  portainer:
     image: portainer/portainer-ce
     container_name: portainer_sub
     restart: unless-stopped
     ports:
       - "9000:9000"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /home/docker/portainer_data:/data
     environment:
       - TZ=America/New_York
     labels:
      - com.centurylinklabs.watchtower.enable=1
