version: '3'

services:
  emby:
    image: emby/embyserver
    container_name: embyserver_sub
    restart: unless-stopped
#    network_mode: host # optional. Uncomment if you want to use DNLA discovery 
    environment:
      - UID=1001
      - GID=113
      - GIDLIST=103
      - TZ=America/New_York
    volumes:
      - /home/docker/config/emby:/config
      - /mnt/sda/jellyfin:/mnt/media
    ports:
      - 8096:8096
      - 8920:8920
#    devices:
#      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    labels:
      - com.centurylinklabs.watchtower.enable=1
