version: "3"
services:
  guacamole:
    image: jwetzell/guacamole:latest
    container_name: guacamole_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ="America/New_York"
    volumes:
      - /home/docker/docker_shared/guacamole:/config
    ports:
      - 5000:8080
    labels:
      - com.centurylinklabs.watchtower.enable=1
