version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin16_sub
    restart: 'unless-stopped'
    network_mode: 'host'
    user: 1001:1001
    group_add:
      - "104"
    environment:
      - TZ=America/New_York
      #- JELLYFIN_PublishedServerUrl=http://jellyfin10.org
    volumes:
      - /mnt/sgt/dockerconf/jellyfin:/config
      - /mnt/sgt/jellyfin/:/media
      - /home/docker:/cache
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card
#    labels:
#      - com.centurylinklabs.watchtower.enable=1
