version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin_sub
    restart: 'unless-stopped'
    network_mode: 'host'
    user: 1001:1001
    group_add:
      - "103"
    environment:
      - TZ=America/New_York
      #- JELLYFIN_PublishedServerUrl=http://jellyfin10.org
    volumes:
      - /mnt/sg8t/dockerconf/jellyfin:/config
      - /mnt/sg8t/jellyfin/:/media
      - /home/docker:/cache
      #- /mnt/sda/jellyfin/movies:/media/movies
      #- /mnt/sda/jellyfin/web:/media/web
      #- /mnt/sda/jellyfin/sounds:/media/sounds
      #- /mnt/sda/jellyfin/tv:/media/tv
      #- /mnt/sg8t:/media/sg8t
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card
#    labels:
#      - com.centurylinklabs.watchtower.enable=1
