version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113; 103
      - TZ=America/New_York
    volumes:
      - /home/docker/config/jellyfin:/config
      - /home/docker/cache/jellyfin:/cache
      - /mnt/sda/jellyfin/:/media
      - /mnt/sda/jellyfin/movies:/media/movies
      - /mnt/sda/jellyfin/web:/media/web
      - /mnt/sda/jellyfin/sounds:/media/sounds
      - /mnt/sda/jellyfin/tv:/media/tv
      - /mnt/usb_sg:/media/usb_sg
    ports:
      - 8098:8096
      - 8922:8920 #optional
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card
    labels:
      - com.centurylinklabs.watchtower.enable=1
