version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin_sub
    restart: unless-stopped
    user: 1001:1001
    group_add:
      - "103"
    environment:
      - TZ=America/New_York
    volumes:
      - /mnt/sg2t/docker_shared/jellyfin/config:/config
      - /home/docker/docker_shared:/cache
      - /mnt/sg2t/jellyfin/:/media
      #- /mnt/sda/jellyfin/movies:/media/movies
      #- /mnt/sda/jellyfin/web:/media/web
      #- /mnt/sda/jellyfin/sounds:/media/sounds
      #- /mnt/sda/jellyfin/tv:/media/tv
      #- /mnt/sg8t:/media/sg8t
    ports:
      - 8098:8096
      - 8922:8920 #optional
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card
#    labels:
#      - com.centurylinklabs.watchtower.enable=1
