version: '3'

services:

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - NB_UMASK=002
    volumes:
      - /mnt/ctdata/docker_shared/jupyter:/home/jovyan/work 
      # In host(lxcUbuntu20), run "usermod -aG users docker", "chown -R docker:users" & "chmod -R 775" on fold "/mnt/ctdata/docker_shared/jupyter" after deployment. 
    ports:
      - "8889:8888"
    labels:
      - com.centurylinklabs.watchtower.enable=1
