version: '3'

services:

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /mnt/ctdata/docker_shared/jupyter:/home/jovyan/work 
      # run "chown -R docker" & "chgrp -R docker" & "chmod -r 777" on fold "/mnt/ctdata/docker_shared/jupyter" after deployment. 
    ports:
      - "8889:8888"
    labels:
      - com.centurylinklabs.watchtower.enable=1
