version: '3'
services:
  lms:
    container_name: lms_sub
    image: lmscommunity/logitechmediaserver
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /home/docker/config/lms:/config:rw
      - /mnt/sda/jellyfin/playlist:/playlist
      - /mnt/sda/jellyfin/music:/music
      - /mnt/sda/jellyfin/:/media
      - /mnt/sda/jellyfin/taotao:/taotao 
      - /mnt/sda/jellyfin/sounds:/sounds
      
    ports:
      - 9089:9089/tcp
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 3483:3483/udp
