version: '3'

services:
######### PERSONAL VIDEO RECORDERS ##########

# Radarr – Movie Download and Management
  radarr:
    image: linuxserver/radarr
    container_name: radarr_sub
    hostname: radarr
    restart: unless-stopped
#   cpus: 1.2 根据CPU核心数设置，4核的话为1.2/4=30%
    ports:
      - 7878:7878
    volumes:
      - /home/docker/config/radarr:/config
      - /mnt/vmdata/radarr:/downloads
      - /mnt/sda/jellyfin/movies:/movies
      - /mnt/vmdata/docker_shared:/shared
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    labels:
      - com.centurylinklabs.watchtower.enable=1
      
# Sonarr – TV Show Download and Management
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr_sub
    hostname: sonarr
    restart: unless-stopped
#   cpus: 1.2 根据CPU核心数设置，4核的话为1.2/4=30%
    ports:
        - 8989:8989
    volumes:
      - /home/docker/config/sonarr:/config
      - /mnt/vmdata/sonarr:/downloads
      - /mnt/sda/jellyfin/tv:/tv
      - /mnt/vmdata/docker_shared:/shared
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    labels:
      - com.centurylinklabs.watchtower.enable=1
      
#LIDARR - Music Download and Management
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr_sub
    hostname: lidarr
    restart: unless-stopped
#   cpus: 1.2 根据CPU核心数设置，4核的话为1.2/4=30%
    ports:
      - 8686:8686
    volumes:
      - /home/docker/config/lidarr:/config
      - /mnt/vmdata/lidarr:/downloads
      - /mnt/sda/jellyfin/music:/music
      - /mnt/vmdata/docker_shared:/shared
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    labels:
      - com.centurylinklabs.watchtower.enable=1
      
# RRShare – YYETS Download and Management
  rrshare:
    image: auska/docker-rrshareweb
    container_name: rrshare_sub
    hostname: rrshare
    restart: unless-stopped
#   cpus: 1.2 根据CPU核心数设置，4核的话为1.2/4=30%
    ports:
      - 3001:3001
      - 6714:6714
      - 30210:30210
    volumes:
      - /home/docker/rrshare:/rrshare
      - /mnt/vmdata/YYETS:/opt/work/store
      - /mnt/vmdata/docker_shared:/shared
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    labels:
      - com.centurylinklabs.watchtower.enable=1
      
######### SEARCHERS ##########

# Jackett – Torrent Proxy
  jackett:
    image: linuxserver/jackett
    container_name: jackett_sub
    hostname: jackett
    restart: unless-stopped
#   cpus: 1.2 根据CPU核心数设置，4核的话为1.2/4=30%
    volumes:
      - /home/docker/config/jackett:/config
      - /mnt/vmdata/jackett:/downloads
      - /mnt/vmdata/docker_shared:/shared
    ports:
      - 9117:9117
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    labels:
      - com.centurylinklabs.watchtower.enable=1
