version: '3'

services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /home/docker/config/jellyfin:/config
      - /mnt/dataCT/cache/jellyfin:/cache
      - /mnt/dataCT/jellyfin/movies:/data/movies
      - /mnt/dataCT/jellyfin/taotao:/data/taotao
      - /mnt/dataCT/jellyfin/youtube:/data/youtube
      - /mnt/dataCT/jellyfin/sounds:/data/sounds
      - /mnt/dataCT/jellyfin/tv:/data/tv
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
