version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113; 103
      - TZ=America/New_York
    volumes:
      - /home/docker/config/jellyfin:/config
      - /home/docker/cache/jellyfin:/cache
      - /mnt/sda/jellyfin/:/media
      - /mnt/sda/jellyfin/movies:/media/movies
      - /mnt/sda/jellyfin/taotao:/media/taotao
      - /mnt/sda/jellyfin/web:/media/web
      - /mnt/sda/jellyfin/sounds:/media/sounds
      - /mnt/sda/jellyfin/tv:/media/tv
    ports:
      - 8098:8096
      - 8922:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
  
  emby:
    image: emby/embyserver
    container_name: embyserver_sub
    restart: unless-stopped
    environment:
      - UID=1001
      - GID=113
      - GIDLIST=103
      - TZ=America/New_York
    volumes:
      - /home/docker/config/emby:/config
#      - /mnt/dataCT/jellyfin/movies:/mnt/movies
      - /mnt/sda/jellyfin:/mnt/media
    ports:
      - 8096:8096
      - 8920:8920
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
