version: "3.8"

services:
  minecraft:
    # Container Image on dockerhub 
    image: itzg/minecraft-server
    container_name: minecraft_sub
    restart: unless-stopped
    tty: true
    stdin_open: true
    # Port Mappings
    ports:
      - "25565:25565"
    # Environment Variables
    environment:
      EULA: "TRUE"
      PUID: "1001"
      PGID: "10001"
      TZ: "America/New_York"
      MEMORY: "6G"
      SERVERNAME: "Canyon Shadow"
      RCON_PASSWORD: "Rcon2012"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /mnt/spcc4t/Dockers/dockerconf/minecraft:/data
    labels:
      - com.centurylinklabs.watchtower.enable=1 
  
