version: "3.8"

services:
  minecraft:
    # Container Image on dockerhub 
    image: itzg/minecraft-server
    container_name: minecraft_sub
    restart: on-failure:3
    tty: true
    stdin_open: true
    # Port Mappings
    ports:
      - "25565:25565"
    # Environment Variables
    environment:
      EULA: "TRUE"
      PUID: "1001"
      PGID: "10001"
      TZ: "America/New_York"
      MEMORY: "2G"
      SERVERNAME: "YUCHENG'S WORLD"
      RCON_PASSWORD: "Testing1076"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /mnt/sgt/dockerconf/minecraft:/data
    labels:
      - com.centurylinklabs.watchtower.enable=1 
  
