version: '3.4'

services:
  
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux_sub
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=America/New_York
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
  db:
    image: postgres:15
    environment:
      - TZ=America/New_York
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    volumes:
      - /mnt/ctdata/docker_shared/postgres:/var/lib/postgresql/data
