version: '3.4'

services:
  
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux_sub
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=America/New_York
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      # 初次使用需要以下三個，否則無法使用
      #- CREATE_ADMIN=1
      #- ADMIN_USERNAME=admin
      #- ADMIN_PASSWORD=test123
    labels:
      - com.centurylinklabs.watchtower.enable=1
  db:
    image: postgres:15
    container_name: postgres_sub
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - /mnt/sgt/dockerconf/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
