version: "3"
services:
  miniboard:
    container_name: miniboard_sub
    image: aceberg/miniboard
    restart: unless-stopped
    ports:
    - 8849:8849
    volumes:
    - ~/.dockerdata/miniboard:/data/miniboard       # app data (set your own path instead of dockerdata)
    - TZ=America/New_York
    environment:
      HOST: "0.0.0.0"         # optional, default: 0.0.0.0
      THEME: "flatly"         # optional, default: flatly
      COLOR: "dark"           # optional, default: dark
    labels:
      - com.centurylinklabs.watchtower.enable=1
