version: '3.8'
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'nginx-proxy-manager_sub'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/ubuntu/dockerconf/nginx-proxy-manager/data:/data
      - /home/ubuntu/dockerconf/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    labels:
      - com.centurylinklabs.watchtower.enable=1
