version: "3.8"

services:
  asu:
    image: openwrt/asu:latest
    container_name: openwrt-asu_sub
    restart: unless-stopped
    ports:
      - "8026:80"        # Web UI
    environment:
      - PUID=1001
      - PGID=10001
      - TZ=America/New_York
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ASU_CACHE_DIR=/cache
    volumes:
      - /mnt/Dockers/dockerconf/asu:/cache
    depends_on:
      - redis
    labels:
      - com.centurylinklabs.watchtower.enable=1

  redis:
    image: redis:7-alpine
    container_name: asu-redis
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
