version: "3.8"

services:
  asu:
    image: openwrtorg/asu:latest
    container_name: openwrt-asu
    restart: unless-stopped
    ports:
      - "8080:80"        # Web UI
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ASU_CACHE_DIR=/cache
    volumes:
      - /mnt/spcc4t/Dockers/dockerconf/asu:/cache
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: asu-redis
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
