version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex_sub
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/docker/docker_shared/plex:/config
      - /mnt/sg2t/taotao:/taotao
    labels:
      - com.centurylinklabs.watchtower.enable=1
