version: '3'

services:
  shaarli:
    image: shaarli/shaarli
    container_name: shaarli_sub
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - /mnt/vmdata/shaarli:/var/www/shaarli/data
    ports:
      - "8091:80"
    labels:
      - com.centurylinklabs.watchtower.enable=1
      
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag_sub
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=mariadb
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag_admin
      - SYMFONY__ENV__DATABASE_PASSWORD=mypassword
      - SYMFONY__ENV__MAILER_HOST=192.168.6.98
      - SYMFONY__ENV__MAILER_USER=notify@mydomain.com
      - SYMFONY__ENV__MAILER_PASSWORD=mypassword      - SYMFONY__ENV__FROM_EMAIL=notify@mydomain.com      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.mydomain.com:443
      - TZ='Asia/Shanghai'
#    ports:
#      - "802:80"
    depends_on:
      - mariadb
      - redis
    volumes:
      - /mnt/bak/docker/wallabag/images:/var/www/wallabag/web/assets/images
      - ${USERDIR}/shared:/shared
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
    # - "traefik.backend=blog"
      - "traefik.frontend.rule=Host:wallabag.mydomain.com"
    # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /wallabag"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
    #not working bash
  # command: ["/shared/wait-for.sh", "mariadb:3306"]
  # stdin_open: true
  # tty: true
  labels:
      - com.centurylinklabs.watchtower.enable=1
      
  mariadb:
    image: mariadb
    container_name: mariadb_sub
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      TZ: 'Asia/Shanghai'
    volumes:
      - /mnt/bak/docker/mariadb:/var/lib/mysql
    labels:
      - com.centurylinklabs.watchtower.enable=1
      
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis_sub
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      - com.centurylinklabs.watchtower.enable=1  
