version: '3'

services:
  rsshub:
    container_name: rsshub_rsshub
    networks:
      - rss-bridge
    browserless:
    networks:
      - rss-bridge
  
  redis:
    networks:
      - rss-bridge

  miniflux:
    image: miniflux/miniflux:latest
    restart: unless-stopped
    container_name: miniflux_sub
    ports:
      - "810:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://miniflux_admin:mypassword@postgres/miniflux?sslmode=disable
      - BASE_URL=https://www.mydomain.com:443/miniflux/
      - RUN_MIGRATIONS=1
      - CERT_FILE=/shared/crt/mydomain.com/mydomain.com.cer
      - KEY_FILE=shared/crt/mydomain.com/mydomain.com.key
      - POLLING_FREQUENCY=60
      - ARCHIVE_READ_DAYS=30
      - CLEANUP_FREQUENCY=30
    volumes:
      - /mnt/bak/docker/shared:/shared:ro

  postgres:
    image: postgres
    container_name: postgres_sub
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypassword
      TZ: 'Asia/Shanghai'
    volumes:
      - /mnt/bak/docker/postgres:/var/lib/postgresql/data
      
  shaarli:
    image: shaarli/shaarli
    container_name: shaarli_sub
    restart: unless-stopped
    environment:
      - TZ='Asia/Shanghai'
    volumes:
      - /mnt/bak/docker/shaarli/data:/var/www/shaarli/data
#    ports:
#      - "800:80"
