version: '3'

services:

  shiori:
    image: radhifadlillah/shiori:latest
    container_name: shiori_sub
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - /mnt/ctdata/docker_shared/shiori:/srv/shiori
    ports:
      - "8082:8080/tcp"
    labels:
      - com.centurylinklabs.watchtower.enable=1
