# https://noted.lol/tutorial-setting-up-shiori/

version: "3"
services:
  shiori:
    image: ghcr.io/go-shiori/shiori
    container_name: shiori20_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - SHIORI_DIR=/data
    ports:
      - 8086:8080
    volumes:
      - /mnt/ctdata/docker_shared/shiori20:/data
    labels:
      - com.centurylinklabs.watchtower.enable=1
