
version: '3.3'

services:

  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: s-pdf_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - DOCKER_ENABLE_SECURITY=false
    ports:
      - 8091:8080
    volumes:
      - /mnt/ctdata/docker_shared/s-pdf/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - /mnt/ctdata/docker_shared/s-pdf/configs:/configs
     labels:
      - com.centurylinklabs.watchtower.enable=1
