version: "3"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing_sub
    hostname: syncthing31 #optional
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /home/docker/docker_shared/syncthing:/config
      - /mnt/ctdata:/ctdata
      - /home:/home
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      - com.centurylinklabs.watchtower.enable=1
