version: '3'
services:
  trilium:
    #container_name: trilium_sub
    image: zadam/trilium:latest
    container_name: trilium_sub
    restart: 'unless-stopped'
    environment:
      - TZ=America/New_York
      - PUID=1001
      - PGID=1001
    volumes:
      - /mnt/ctdata/docker_shared/trilium-data:/home/node/trilium-data
    ports:
      - 8087:8080
    labels:
      - com.centurylinklabs.watchtower.enable=1
   
