version: '3'
services:
  trilium:
    image: triliumnext/trilium:latest
    container_name: triliumnext_sub
    restart: 'unless-stopped'
    environment:
      - TZ=America/New_York
      - USER_UID=1001
      - USER_GID=10001
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    volumes:
      - /mnt/sgt/dockerconf/trilium-data:/home/node/trilium-data
    ports:
      - 8087:8080
    labels:
      - com.centurylinklabs.watchtower.enable=1
   
