version: '3'

services:

  wireguard:
    image: lscr.io/linuxserver/wireguard:v1.0.20210914-ls72
    container_name: wireguard_sub
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - SERVERURL=faith4.duckdns.org
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - LOG_CONFS=true #optional
    volumes:
      - /mnt/ctdata/docker_shared/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    #labels:
    #  - com.centurylinklabs.watchtower.enable=1
