version: '3'

services:

  Jeeaaasus-youtube-dl:
    image: jeeaaasustest/youtube-dl
    container_name: youtube-dl_sub
    restart: unless-stopped
    environment:
#      - youtubedl_webui=true
#      - youtubedl_webuiport=8082
      - youtubedl_interval=1h
      - youtubedl_quality=720
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/docker/docker_shared/youtube-dl:/config
      - /mnt/sg2t/ytdl:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=1

  metube:
    image: alexta69/metube
    container_name: metube_sub
    restart: unless-stopped
    environment:
      - UID=1001
      - GID=1001
      - TZ=America/New_York
      - YTDL_OPTIONS={"writesubtitles": true, "subtitleslangs": ["en", "-live_chat"], "postprocessors": [{"key": "FFmpegEmbedSubtitle", "already_have_subtitle": false}, {"key": "FFmpegMetadata", "add_chapters": true}]}
    ports:
      - "8085:8081"
    volumes:
      - /mnt/sg2t/ytdl/Metu:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=1

  ytdl_material:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl-material_sub
    restart: unless-stopped
    environment: 
      UID: 1001
      GID: 1001
      TZ: 'America/New_York'
      ALLOW_CONFIG_MUTATIONS: 'true'
      ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
      ytdl_use_local_db: 'false'
      write_ytdl_config: 'true'
    depends_on:
      - ytdl-mongo-db
    ports:
      - "8086:17442"
    volumes:
      - /mnt/sg2t/ytdl/appdata:/app/appdata
      - /mnt/sg2t/ytdl/audio:/app/audio
      - /mnt/sg2t/ytdl/video:/app/video
      - /mnt/sg2t/ytdl/subscriptions:/app/subscriptions
      - /mnt/sg2t/ytdl/users:/app/users
    labels:
      - com.centurylinklabs.watchtower.enable=1
      
  ytdl-mongo-db:
    image: mongo
    container_name: mongo-db_sub
    restart: unless-stopped
    environment: 
      UID: 1001
      GID: 1001
      TZ: 'America/New_York'
    ports:
      - "27017:27017"
    logging:
      driver: "none"          
    volumes:
      - /mnt/sg2t/ytdl/db/:/data/db
    labels:
      - com.centurylinklabs.watchtower.enable=1
