version: '3'

services:

  Jeeaaasus-youtube-dl:
    image: jeeaaasustest/youtube-dl
    container_name: youtube-dl_sub
    restart: unless-stopped
    environment:
      - youtubedl_interval=1h
      - youtubedl_quality=720
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /mnt/vmdata/youtube-dl:/config
      - /mnt/vmdata/youtube-dl:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=1
  
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
    volumes:
      - /mnt/vmdata/youtube-dl:/var/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    #sysctls:
    #  - net.core.rmem_max=2097152
    labels:
      - com.centurylinklabs.watchtower.enable=1
