version: '3'

services:

  Jeeaaasus-youtube-dl:
    image: jeeaaasustest/youtube-dl
    container_name: youtube-dl_sub
    restart: unless-stopped
    environment:
#      - youtubedl_webui=true
#      - youtubedl_webuiport=8082
      - youtubedl_interval=1h
      - youtubedl_quality=720
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/docker/docker_shared/youtube-dl:/config
      - /mnt/sg2t/ytdl:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=1

  metube:
    image: alexta69/metube
    container_name: metube_sub
    restart: unless-stopped
    environment:
      - UID=1001
      - GID=1001
      - TZ=America/New_York
      - YTDL_OPTIONS={"writesubtitles": true, "subtitleslangs": ["en", "-live_chat"], "postprocessors": [{"key": "Exec", "exec_cmd": "chmod 0664", "when": "after_move"}, {"key": "FFmpegEmbedSubtitle", "already_have_subtitle": false}, {"key": "FFmpegMetadata", "add_chapters": true}]}
    ports:
      - "8085:8081"
    volumes:
      - /mnt/sg2t/ytdl/Metu:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=1
