version: '3'

services:

  Jeeaaasus-youtube-dl:
    image: jeeaaasustest/youtube-dl
    container_name: youtube-dl_sub
    restart: unless-stopped
    environment:
      - youtubedl_interval=1h
      - youtubedl_quality=720
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /mnt/vmdata/youtube-dl:/config
      - /mnt/vmdata/youtube-dl:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=1
  
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing_sub
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=113
      - TZ=America/New_York
    volumes:
      - /home/docker/config/syncthing:/config
      - /mnt/vmdata:/vmdata
      - /mnt/sda:/sda
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    labels:
      - com.centurylinklabs.watchtower.enable=1
